export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const SELECT_REDDIT = 'SELECT_REDDIT';
export const INVALIDATE_REDDIT = 'INVALIDATE_REDDIT';

export const REQUEST_SPRODUCT_LIST = 'REQUEST_SPRODUCT_LIST';
export const RECEIVE_SPRODUCT_LIST = 'RECEIVE_SPRODUCT_LIST';
export const SELECT_SPRODUCT_ITEM = 'SELECT_SPRODUCT_ITEM';
export const INVALIDATE_SPRODUCT_LIST = 'INVALIDATE_SPRODUCT_LIST';
